name: "avito-shop-tests"

services:
  avito-shop-integration-tests:
    build:
      dockerfile: Dockerfile
      target: tests
      context: .
    networks:
      internal:
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: postgres-tests
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-shop_test}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop_test'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal: