postgres:
  host: localhost
  port: 5432
  user: postgres
  password: password
  database: shop
  poolSize: 20
auth:
  secretKey: "fchg678q314fgia7uywe7rfg798i4q"
app:
  host: "localhost"
  port: 8080